service: s3-cross-account
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-west-2

  iam:
    role:
      statements:
        - Effect: Allow
          Action: s3:*
          Resource: '*'

plugins:
  - serverless-plugin-typescript

functions:
  s3upload:
    handler: src/s3upload.handler
    events:
      - httpApi:
          method: GET
          path: /s3/upload
