service: s3-cross-account
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-west-2

  iam:
    role:
      name: 'jayLambdaDefaultRole'
      statements:
        - Effect: Allow
          Action:
            - 's3:*'
          Resource:
            - '*'
        - Effect: Allow
          Action:
            - 'sts:*'
          Resource:
            - 'arn:aws:iam::11111111:role/jay-cross-account-assume-role'

plugins:
  - serverless-plugin-typescript

functions:
  s3upload:
    handler: src/s3upload.handler
    events:
      - httpApi:
          method: POST
          path: /s3/sync
    environment:
      roleArn: ''
      sourceBucket: ''
      destBucket: ''

resources:
  Resources:
    jayAssumeRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: 'jayAssumeRole'
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - sts:AssumeRole
              Principal:
                Service:
                  - lambda.amazonaws.com
