service: vanila-ts

frameworkVersion: '3'

provider:
  name: aws
  region: eu-west-2
  runtime: nodejs16.x
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:*
          Resource: 
            Fn::GetAtt:
              - JayServerlessS3Bucket
              - Arn
          
  environment:
    BUCKET_NAME: jay-serverless-bucket  
custom:
  logRetentionInDays: 1
  

plugins:
  - serverless-plugin-typescript
  - serverless-plugin-log-retention
  - serverless-s3-local
  - serverless-offline

functions:
  get:
    handler: src/handlers/s3Handler.get
    events:
      - httpApi:
          path: /hello
          method: get

resources:
  Resources:
    JayServerlessS3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:provider.environment.BUCKET_NAME}
