service: vanila-ts

frameworkVersion: '3'

provider:
  name: aws
  region: eu-west-2
  runtime: nodejs16.x
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:*
          Resource: 
            Fn::GetAtt:
              - JayServerlessS3Bucket
              - Arn
          
  environment:
    BUCKET_NAME: jay-serverless-bucket-2  
  httpApi:
    cors: true
    authorizers:
      apiAuthoriser:
        type: request
        functionName: authoriser

custom:
  logRetentionInDays: 1
  

plugins:
  - serverless-plugin-typescript
  - serverless-plugin-log-retention
  - serverless-s3-local
  - serverless-offline

functions:
  authoriser:
    handler: src/handlers/authoriser.handler
  helloApi:
    handler: src/handlers/helloApi.handler
    events:
      - httpApi:
          path: /helloapi
          method: get          
          authorizer:
            name: apiAuthoriser
  s3ListObjects:
    handler: src/handlers/s3ListObjects.handler
    events:
      - httpApi:
          path: /s3listobjects
          method: get


resources:
  Resources:
    JayServerlessS3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:provider.environment.BUCKET_NAME}
